name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'build.zig'
      - 'scripts/**'

jobs:
  build-check:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.13.0

    - name: Install Build Tools
      shell: pwsh
      run: |
        choco install make ninja -y
        $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")

    # Just check if it compiles
    - name: Basic Compilation Check
      shell: pwsh
      run: make check 